<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>example.junit</groupId>
    <artifactId>osgi-junit-extender-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>it-harness</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.osgi</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>junit-import-extender</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>fixture-production</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>fixture-tests-fragment</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>fixture-ordinary-tests</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>execution-app-fixture</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>alternative-junit-provider</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>example.junit</groupId>
      <artifactId>alternative-hamcrest-provider</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>stage-bundles</id>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/bundles</outputDirectory>
              <artifactItems>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>junit-import-extender</artifactId>
                  <version>${project.version}</version>
                  <destFileName>junit-import-extender.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>fixture-production</artifactId>
                  <version>${project.version}</version>
                  <destFileName>fixture-production.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>fixture-tests-fragment</artifactId>
                  <version>${project.version}</version>
                  <destFileName>fixture-tests-fragment.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>fixture-ordinary-tests</artifactId>
                  <version>${project.version}</version>
                  <destFileName>fixture-ordinary-tests.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>execution-app-fixture</artifactId>
                  <version>${project.version}</version>
                  <destFileName>execution-app-fixture.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>alternative-junit-provider</artifactId>
                  <version>${project.version}</version>
                  <destFileName>alternative-junit-provider.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>example.junit</groupId>
                  <artifactId>alternative-hamcrest-provider</artifactId>
                  <version>${project.version}</version>
                  <destFileName>alternative-hamcrest-provider.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.eclipse.platform</groupId>
                  <artifactId>org.eclipse.osgi</artifactId>
                  <version>3.24.300</version>
                  <destFileName>framework.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.eclipse.platform</groupId>
                  <artifactId>org.eclipse.equinox.app</artifactId>
                  <version>1.7.600</version>
                  <destFileName>app.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.eclipse.platform</groupId>
                  <artifactId>org.eclipse.equinox.registry</artifactId>
                  <version>3.12.600</version>
                  <destFileName>registry.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.eclipse.platform</groupId>
                  <artifactId>org.eclipse.equinox.common</artifactId>
                  <version>3.20.300</version>
                  <destFileName>common.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.apache.servicemix.bundles</groupId>
                  <artifactId>org.apache.servicemix.bundles.junit</artifactId>
                  <version>4.13.2_1</version>
                  <destFileName>servicemix.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <failIfNoTests>true</failIfNoTests>
          <systemPropertyVariables>
            <it.scenarios>${it.scenarios}</it.scenarios>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <properties>
    <it.scenarios>all</it.scenarios>
  </properties>
</project>
