junit.extensions=junit.extensions.ActiveTestSuite
junit.framework=junit.framework.Assert
junit.runner=junit.runner.BaseTestRunner
junit.textui=junit.textui.ResultPrinter
org.hamcrest=org.hamcrest.BaseDescription
org.hamcrest.core=org.hamcrest.core.AllOf
org.hamcrest.internal=org.hamcrest.internal.ArrayIterator
org.junit=org.junit.After
org.junit.experimental=org.junit.experimental.ParallelComputer
org.junit.experimental.categories=org.junit.experimental.categories.Categories
org.junit.experimental.max=org.junit.experimental.max.CouldNotReadCoreException
org.junit.experimental.results=org.junit.experimental.results.FailureList
org.junit.experimental.runners=org.junit.experimental.runners.Enclosed
org.junit.experimental.theories=org.junit.experimental.theories.DataPoint
org.junit.experimental.theories.internal=org.junit.experimental.theories.internal.AllMembersSupplier
org.junit.experimental.theories.suppliers=org.junit.experimental.theories.suppliers.TestedOn
org.junit.function=org.junit.function.ThrowingRunnable
org.junit.internal=org.junit.internal.ArrayComparisonFailure
org.junit.internal.builders=org.junit.internal.builders.AllDefaultPossibilitiesBuilder
org.junit.internal.management=org.junit.internal.management.FakeRuntimeMXBean
org.junit.internal.matchers=org.junit.internal.matchers.StacktracePrintingMatcher
org.junit.internal.requests=org.junit.internal.requests.ClassRequest
org.junit.internal.runners=org.junit.internal.runners.ClassRoadie
org.junit.internal.runners.model=org.junit.internal.runners.model.EachTestNotifier
org.junit.internal.runners.rules=org.junit.internal.runners.rules.RuleMemberValidator
org.junit.internal.runners.statements=org.junit.internal.runners.statements.ExpectException
org.junit.matchers=org.junit.matchers.JUnitMatchers
org.junit.rules=org.junit.rules.DisableOnDebug
org.junit.runner=org.junit.runner.Computer
org.junit.runner.manipulation=org.junit.runner.manipulation.Alphanumeric
org.junit.runner.notification=org.junit.runner.notification.Failure
org.junit.runners=org.junit.runners.AllTests
org.junit.runners.model=org.junit.runners.model.Annotatable
org.junit.runners.parameterized=org.junit.runners.parameterized.BlockJUnit4ClassRunnerWithParameters
org.junit.validator=org.junit.validator.AnnotationValidator
